env:
  browser: true
  commonjs: true
  es2020: true
  node: true
  mocha: true
extends:
  - standard
  - "plugin:@typescript-eslint/recommended"
  - "plugin:security/recommended"
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - security
parserOptions:
  ecmaVersion: 11
rules:
  '@typescript-eslint/no-var-requires': 0
  'no-throw-literal': 0
