version: 2.1
orbs:
  node: circleci/node@10.21.0
jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test